### ISSUE TITLE
Kinetic installation failed (MacOs Sierra)

### ISSUE THREAD

**Issue by aaramirezd** [ros-gbp/qt_gui_core-release#2]
Hi,

I tried to install kinetic on Mac Pro with MacOs Sierra but failed.

==> Processing catkin package: 'qt_gui_cpp'
==> Building with env: '/Users/Andres/ros_catkin_ws/install_isolated/env.sh'
Makefile exists, skipping explicit cmake invocation...
==> make cmake_check_build_system in '/Users/Andres/ros_catkin_ws/build_isolated/qt_gui_cpp'
==> make -j4 -l4 in '/Users/Andres/ros_catkin_ws/build_isolated/qt_gui_cpp'
[  5%] Linking CXX shared library /Users/Andres/ros_catkin_ws/devel_isolated/qt_gui_cpp/lib/libqt_gui_cpp.dylib
[ 83%] Built target qt_gui_cpp
[ 88%] Running SIP generator for qt_gui_cpp_sip Python bindings...
Traceback (most recent call last):
  File "/Users/Andres/ros_catkin_ws/install_isolated/share/python_qt_binding/cmake/sip_configure.py", line 8, in <module>
    from PyQt5 import QtCore
ImportError: No module named PyQt5
make[2]: *** [sip/qt_gui_cpp_sip/Makefile] Error 1
make[1]: *** [src/qt_gui_cpp_sip/CMakeFiles/libqt_gui_cpp_sip.dir/all] Error 2
make: *** [all] Error 2
<== Failed to process package 'qt_gui_cpp': 
  Command '['/Users/Andres/ros_catkin_ws/install_isolated/env.sh', 'make', '-j4', '-l4']' returned non-zero exit status 2

Reproduce this error by running:
==> cd /Users/Andres/ros_catkin_ws/build_isolated/qt_gui_cpp && /Users/Andres/ros_catkin_ws/install_isolated/env.sh make -j4 -l4

Command failed, exiting.
MacBook-Andres:ros_catkin_ws Andres$ 

I installed python, python3, qt5 and pyqt5 with brew.

the output of brew info pyqt5 is:

pyqt5: stable 5.7.1 (bottled)
Python bindings for v5 of Qt
https://www.riverbankcomputing.com/software/pyqt/download5
/usr/local/Cellar/pyqt5/5.7.1_1 (830 files, 26M) *
  Poured from bottle on 2017-02-14 at 15:28:07
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/pyqt5.rb
==> Dependencies
Required: qt@5.7 ✔, sip --with-python3 ✔
==> Requirements
Recommended: python3 ✔
Optional: python ✔
==> Options
--with-debug
	Build with debug symbols
--with-docs
	Install HTML documentation and python examples
--with-python
	Build with python support
--without-python3
	Build without python3 support

Do you have any idea how to solve this problem?

Thanks
Andrés

**Comment by dirk-thomas** [comment]
I am not sure if you have seen the [ROS support guidelines](http://wiki.ros.org/Support) but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rational for asking all kind of questions in a single place is:
* There are many more people reading questions there so your chances on getting an answer and in a timely manner are much higher.
* In the future other users will search there for similar problems and can find your question and the potential answers.
* The issue tracker in this repo is used to track bugs, feature requests, etc. But your question is not such an action item.

Therefore I will close this ticket here for now. If you have asked your question on answers.ros.org please feel free to add a link to the question to this ticket so that future readers can find the related question.
